export { default as backBlackIcon } from './icon-back-black.png';
export { default as backGreyIcon } from './icon-back-grey.png';
export { default as backPrimaryIcon } from './icon-back-primary.png';
export { default as nextIcon } from './icon-next-icon.png';
export { default as progressCircleImg } from './image-progress-circle.jpg';
export { default as progressGreyImg } from './image-progress-grey.jpg';
export { default as progressPrimaryImg } from './image-progress-primary.jpg';
export { default as surveyDoneImg } from './image-survey-done.png';
export { default as surveyImg } from './image-survey.png';
